apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: arti-test-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: arti-test-nodejs 
  name: arti-test-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: arti-test-nodejs 
